title: amazing-dinner-course
tagline: A brand new course on Learning Lab
description: hello
template:
  repo: amazing-dinner-course-template
  name: amazing-dinner-course
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course!
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
